# Permalinks
#
permalink: :title:output_ext

# Setup
title:               map's blog
tagline:             'writing into the void'
url:                 https://blog.map.wtf
baseurl:             ''
plugins:                [jekyll-paginate]
paginate:            5
paginate_path: "page:num"

# Custom vars
version:             1.0.0